services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testme123
  webapp:
    build: .
    image: djangopolls:latest
    container_name: django
    environment:
      - DEBUG=on
      - SECRET_KEY="wb1j9+vxe2b#1dfu+2zgiaoa1v@q@wub15i75r=!*mol39k-qo"
      - DATABASE_URL=postgres://postgres:testme123@db:5432/postgres
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - REDIS_HOST=redis
      - USE_S3=off
      - AWS_S3_ACCESS_KEY_ID=admin
      - AWS_S3_SECRET_ACCESS_KEY=testme123
      - AWS_STORAGE_BUCKET_NAME=mdt-ont
      - AWS_S3_ENDPOINT_URL=http://minio:9000/
      - AWS_S3_CUSTOM_DOMAIN=localhost:9000/mdt-ont
      - AWS_S3_USE_SSL=off
    ports:
      - "8000:8994"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    depends_on:
      - db
      - redis
      - minio
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  av:
    image: clamav/clamav:stable_base
    container_name: av
    volumes:
      - ./data/av:/var/lib/clamav
  minio:
    image: 'bitnami/minio:latest'
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=testme123
      - MINIO_DEFAULT_BUCKETS=mdt-ont
    volumes:
      - ./data/minio:/bitnami/minio/data